 #+SEQ_TODO: DG (g) | DONE(d) 

* January
** 28
*** goals
- [X] Complete Habits
- [X] Read to at least 35% of GTD
- [X] Do at least 30 pull ups
*** notes

Today went well, I read GTD some more, and that gave me some more motivation to be productive and organized. Obviously it's been a bit of a rocky road since I started Jan 1 more or less, but I think it's a good sign 
i've been able to stick with things this far more or less. I'm still experimenting with how I organize myself. But, I think the initial time investment is starting to become worth it. I think this could be a really productive system for me. 

I went to Veronica's interview on a local Christian TV station. It was ano hour long, and she did an amazing job, playing 4 of her songs and discussing what her trajectory as a Honduran artist has been like.

** 29
*** goals
- [X] Get Vero to go on a walk
- [ ] Read to at least 60% of GTD
- [X] Make Veggie Burgers for Vero
** 30
*** goals
    - [X] yoga
    - [ ] eat before traveling
    - [X] relax and enjoy
** 31 
*** G goals [0/3]
**** DG create forrestnaylor@mayatan.org email account - Jan 31
**** DG have fun with Maria, Ben and Vero - Jan 31
**** DG work on system to log words on phone and share with emacs - Jan 31
*** entry
