
* URLS
[[http://cachestocaches.com/archive/][caches to cahces (programmer/physicist/etc)]]





* Contacts 
* Quotes
** When you are in a hole, stop digging.
- Will Rogers
 Entered on [2021-01-27 mié 19:18]
  
   [[file:~/.emacs.d/init.el::))]]
** Don't just do something. Stand there.
- Rochelle Myer
 Entered on [2021-01-27 mié 19:18]
  
   [[file:~/.emacs.d/GTD/reference.org::*Quotes][Quotes]]
** Simple , clear purpose and principles give rise to complex and intelligent behavior. Complex rules and regulations give rise to simple and stupid behavior.
- Dee Hock
 Entered on [2021-01-27 mié 19:25]
  
   [[file:~/.emacs.d/GTD/reference.org::*Quotes][Quotes]]
** I always wanted to be somebody. I should have been more specific.
- Lily Tomlin
 Entered on [2021-01-27 mié 19:32]
  
   [[file:~/.emacs.d/GTD/reference.org::*Quotes][Quotes]]
** The best way to get a good idea is to get lots of ideas.
- Linus Pauling
 Entered on [2021-01-27 mié 19:34]
  
   [[file:~/.emacs.d/GTD/reference.org::*Quotes][Quotes]]
** Only he who handles his ideas lightly is master of his ideas, and only he who is master of his ideas is not enslaved by them.
- Lin Yutang
 Entered on [2021-01-27 mié 19:41]
  
   [[file:~/.emacs.d/GTD/reference.org::*The best way to get a good idea is to get lots of ideas.][The best way to get a good idea is to get lots of ideas.]]
** Seat's taken
- Billy Regan
 Entered on [2021-01-27 mié 19:42]
  
   [[file:~/.emacs.d/GTD/reference.org::*Only he who handles his ideas lightly is master of his ideas, and only he who is master of his ideas is not enslaved by them.][Only he who handles his ideas lightly is master of his ideas, and only he who is master of his ideas is not enslaved by them.]]
** Don't be afraid to take a big step if one is indicated. You can't cros a chasm in two small jumps.
- David L. George
 Entered on [2021-01-28 jue 10:14]
  
   [[file:~/.emacs.d/GTD/reference.org::*Quotes][Quotes]]
** What lies in our power to do, lies in our power not to do.
** Every now and then go away and have a little relaxation. To reamin constantly at work will diminish your judgment. Go some distance away, because work will be in perspective and a lack of harmony is more readily seen.
- Leonardo da Vinic
** In order to understand the world, on has to run away from it on ocassion.

-- Albert Camus
**  The message is: positive future thinking is critical and fabulous, but it's most effectively manifested when it is tied to a confidence of execution in  the material world, with responsiveness and course correction built in.
 Source: GTD
** You have freedom when you are easy in your harness.
 Source: Robert Frost
** We all have times when we think more effectively, and times when we should not be thinking at all.
 Source: Danile Cohen 
** Success is learning to deal with plan B.
 Source: 
** To ignore the unexpected (even if it were possible) would be to live without opportunity, spontaneity, and the rich moments of which "life" is made.
 Source: Stephen Covey
** Your work is to discover your work and then with all your heart to give yourself to it.
 Source: Buddha
** The best place to succeed is where you are with waht you have.
 Source: Charles Schwab
** Pick battles big enough to matter, small enough to win
 Source: Jonathan Kozol
** Neutral is a state where you are not jumping ahead too quickly or moving too slow. Neutral does not mean being inactive, complacent, or passive. It's about a calm poise that alllows for new information and new possibliites to emerge before taking further action. When in neutral you actually increase your sensitivity and intuitive intelligence. Neutral is feritle ground for new possibilites to grow from.
 Source: Doc Childre
