
* URLS
[[http://cachestocaches.com/archive/][caches to cahces (programmer/physicist/etc)]]





* Contacts 
* Quotes
** When you are in a hole, stop digging.
- Will Rogers
 Entered on [2021-01-27 mié 19:18]
  
   [[file:~/.emacs.d/init.el::))]]
** Don't just do something. Stand there.
- Rochelle Myer
 Entered on [2021-01-27 mié 19:18]
  
   [[file:~/.emacs.d/GTD/reference.org::*Quotes][Quotes]]
** Simple , clear purpose and principles give rise to complex and intelligent behavior. Complex rules and regulations give rise to simple and stupid behavior.
- Dee Hock
 Entered on [2021-01-27 mié 19:25]
  
   [[file:~/.emacs.d/GTD/reference.org::*Quotes][Quotes]]
** I always wanted to be somebody. I should have been more specific.
- Lily Tomlin
 Entered on [2021-01-27 mié 19:32]
  
   [[file:~/.emacs.d/GTD/reference.org::*Quotes][Quotes]]
** The best way to get a good idea is to get lots of ideas.
- Linus Pauling
 Entered on [2021-01-27 mié 19:34]
  
   [[file:~/.emacs.d/GTD/reference.org::*Quotes][Quotes]]
** Only he who handles his ideas lightly is master of his ideas, and only he who is master of his ideas is not enslaved by them.
- Lin Yutang
 Entered on [2021-01-27 mié 19:41]
  
   [[file:~/.emacs.d/GTD/reference.org::*The best way to get a good idea is to get lots of ideas.][The best way to get a good idea is to get lots of ideas.]]
** Seat's taken
- Billy Regan
 Entered on [2021-01-27 mié 19:42]
  
   [[file:~/.emacs.d/GTD/reference.org::*Only he who handles his ideas lightly is master of his ideas, and only he who is master of his ideas is not enslaved by them.][Only he who handles his ideas lightly is master of his ideas, and only he who is master of his ideas is not enslaved by them.]]
** Don't be afraid to take a big step if one is indicated. You can't cros a chasm in two small jumps.
- David L. George
 Entered on [2021-01-28 jue 10:14]
  
   [[file:~/.emacs.d/GTD/reference.org::*Quotes][Quotes]]
** What lies in our power to do, lies in our power not to do.
** Every now and then go away and have a little relaxation. To reamin constantly at work will diminish your judgment. Go some distance away, because work will be in perspective and a lack of harmony is more readily seen.
- Leonardo da Vinic
** In order to understand the world, on has to run away from it on ocassion.

-- Albert Camus
**  The message is: positive future thinking is critical and fabulous, but it's most effectively manifested when it is tied to a confidence of execution in  the material world, with responsiveness and course correction built in.
 Source: GTD
** You have freedom when you are easy in your harness.
 Source: Robert Frost
** We all have times when we think more effectively, and times when we should not be thinking at all.
 Source: Danile Cohen 
** Success is learning to deal with plan B.
 Source: 
** To ignore the unexpected (even if it were possible) would be to live without opportunity, spontaneity, and the rich moments of which "life" is made.
 Source: Stephen Covey
** Your work is to discover your work and then with all your heart to give yourself to it.
 Source: Buddha
** The best place to succeed is where you are with waht you have.
 Source: Charles Schwab
** Pick battles big enough to matter, small enough to win
 Source: Jonathan Kozol
** Neutral is a state where you are not jumping ahead too quickly or moving too slow. Neutral does not mean being inactive, complacent, or passive. It's about a calm poise that alllows for new information and new possibliites to emerge before taking further action. When in neutral you actually increase your sensitivity and intuitive intelligence. Neutral is feritle ground for new possibilites to grow from.
 Source: Doc Childre
** The secret of getting ahead is getting started. The secret of getting started is breaking your complex overwhelming tasks into small, manageable tasks, and then starting on the first one.
 Source: Mark Twain
** I am an old man, and I have known a great many troubes, but most of them never happened.
 Source: Mark Twain
** No matter how big and tough a problem may be, get rid of confusion by taking one little step toward solution. Do something.
 Source: George F. Nordenholt
** Talk does not cook rice.
 Source: Chinese proverb
** There are risks and costs to a program of action, but they are far less than the long-range risks and costs of comfortable inaction.n
 Source: John F. Kennedy
** Start by doing what's necessary, then what's possible, and suddenly you are doing the impossible.
 Source: Saint Francis of Assisi
** There are only two problems in life: (1) you know what you want, and you don't know how to get it; and/or (2) you don't know what you want
 Source: Steven Snyder
** Life affords no higher pleasure than that of the surmounting difficulties, passing from one step of success to another, forming new wishes, and seeing them gratified.
 Source: Dr. Samuel Johnson
** An idealist believes that the short run doesn't count/ A cynic believes the long run doesn't matter. A realist believes that what is done or left undone in the short run determines the long run.
 Source: Sydney J. Harris
** I respect the man who knows distinctly what he wishes. The greater part of a ll mischief in the world arises from the fact that men do not sufficiently understand their own aims. Thye have undertaken to build a tower, and spend no more labor on the foundation than would be necessary to erect a hut.
 Source: Johann Wolfgang von Goethe
** A vision without a task is but a dream; a task without a vision is but drudgery; a vision and a task is the hope of the world.
 Source: From a church in Sussex, England, ca. 1730
** passwordstore - commandline program
 Source: 
** It is a ridiculous thing for a man not to fly from his own badness, which is indeed possible, but to fly from other men's badness, which is impossible.
 Source: Marcus Aurelius
