
* 2021
** 2021-01 January
*** 2021-01-09 Saturday
**** TODO AM GOALS [2/4]
     SCHEDULED: <2021-01-09 Sat>
1) [X] Work on emacs capture templates

2) [ ] Buy a plane ticket

3) [ ] Research flight covid testing requirements

4) [X] Spend time with Killian and Coleen
    Entered on [2021-01-09 Sat 11:22]
  

Today I organized some, ate pretty unhealthily, but  was not especially productive. I at least got my morning routine in though! 

Talking with Vero was good, but the scheduling is bad. It is too late for me, and I can tell that Vero is a little annoyed by only talking for a little while. She wants to relax and talk more. Have to figure that out somehow. Time will tell!

Sending out an email to Cindy Knipp's friend, and power teacher at McDonongh - Mary Catherine to give her a resume so McDonogh can have me on the radar potentially!

Also started filling out some info for Varsity tutors, which could be valuable as an online teaching possibilit going forward, to make some money!

Would not mind getting Vero an apple watch, but not totally sure it's a great idea. Also lingere may be something I should get!
