* Personal statement

I am a graduate of Bates College in Lewiston, Maine with a B.A. in physics and minors in mathematics and rhetoric. I spent a semester classroom teaching IB physics in Mexico City before working in Nicaragua this past year as a tutor. Ironically, math and science were some of the most difficult subjects for me as a student. I know what it is like when that material does not come easily. Fortunately, I was able to overcome my personal obstacles in those fields and attain an excellent academic standing in those subjects. Over time I have realised there is no such thing as being "bad" at science. I love helping my students come to that realisation as well. Tutoring helps me avoid a "one size fits all" style of teaching and instead use students' strengths to help them master material. Some of my interests outside teaching and tutoring include: Languages - arabic and spanish Literature - science fiction and fantasy Music - Piano

* Interests/Hobbies
Languages (arabic and spanish), Science Fiction, piano
